stages:
  - build
  - deploy

variables:
  REGION: europe-west1
  PROJECT_ID: just-slots-499010
  REPOSITORY: game-backend
  IMAGE: $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/api

# -------------------------
# BUILD
# -------------------------
backend:build:
  stage: build
  image: docker:24
  services:
    - docker:dind

  script:
    - |
      if [ "$CI_COMMIT_BRANCH" = "dev" ]; then
        TAG="dev"
      elif [ "$CI_COMMIT_BRANCH" = "staging" ]; then
        TAG="staging"
      elif [ "$CI_COMMIT_BRANCH" = "main" ]; then
        TAG="prod"
      else
        echo "No build"
        exit 0
      fi

    - docker buildx create --use

    - |
      docker buildx build \
        --platform linux/amd64 \
        -t $IMAGE:$TAG \
        --push \
        ./apps/game-backend

# -------------------------
# DEPLOY
# -------------------------
backend:deploy:
  stage: deploy
  image: google/cloud-sdk:slim
  script:
    - echo "=== DEPLOY START ==="

    - |
      if [ "$CI_COMMIT_BRANCH" = "dev" ]; then
        ENV="dev"
      elif [ "$CI_COMMIT_BRANCH" = "staging" ]; then
        ENV="staging"
      elif [ "$CI_COMMIT_BRANCH" = "main" ]; then
        ENV="prod"
      else
        exit 0
      fi

    - gcloud config set project $PROJECT_ID
    - gcloud container clusters get-credentials cluster-dev --region us-central1

    # IMPORTANT: match TAG from build
    - kubectl set image deployment/game-backend-$ENV backend=$IMAGE:$ENV
    - kubectl rollout status deployment/game-backend-$ENV

    # smoke test
    - |
      if [ "$ENV" = "dev" ]; then
        URL="http://api-dev-justslots.duckdns.org"
      elif [ "$ENV" = "staging" ]; then
        URL="http://api-staging-slots.duckdns.org"
      else
        URL="http://api-slots.duckdns.org"
      fi

    - sleep 10
    - curl -f $URL/health || echo "Smoke test failed"

  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == "staging"
      when: manual
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
