stages:
  - build
  - deploy

variables:
  REGION: europe-west1
  PROJECT_ID: just-slots-499010
  REPOSITORY: game-backend
  IMAGE: $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/api

backend:build:
  stage: build
  image: docker:24
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - echo "=== Backend Build ==="

    - docker build -t $IMAGE:$CI_COMMIT_SHA ./apps/game-backend
    - docker tag $IMAGE:$CI_COMMIT_SHA $IMAGE:latest

    - echo "$GCP_SERVICE_KEY" | docker login -u _json_key --password-stdin https://$REGION-docker.pkg.dev

    - docker push $IMAGE:$CI_COMMIT_SHA
    - docker push $IMAGE:latest

backend:deploy:
  stage: deploy
  image: google/cloud-sdk:slim
  script:
    - echo "$GCP_SERVICE_KEY" > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project $PROJECT_ID
    - gcloud container clusters get-credentials just-slots-dev --region $REGION

    - kubectl set image deployment/game-backend backend=$IMAGE:$CI_COMMIT_SHA
    - kubectl rollout status deployment/game-backend

  only:
    - main
