client:build:
  stage: build
  image: node:20
  script:
    - cd apps/game-client/game-client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - apps/game-client/game-client/dist

client:deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - echo "$GCP_SERVICE_KEY" > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gsutil -m rsync -r apps/game-client/game-client/dist gs://just-slots-fe
  only:
    - main
